<?xml version = "1.0"?>

<!--Defining Robot-->
<robot name = "differential_drive" xmlns:xacro = "http://www.ros.org/wiki/xacro">

		<!--Defining Constants-->
		<xacro:property name="M_PI" value="3.141	5926535897931" />
		<xacro:property name="M_PI_2" value="1.570796327" />
		<xacro:property name="DEG_TO_RAD" value="0.017453293" />

		<!--Defining Materials-->
		<!--Defining Black Material-->
		<material name = "Black">
			<color rgba = "0 0 0 1"/>
		</material>

		<!--Defining White Material-->
		<material name = "White">
			<color rgba = "1 1 1 1"/>
		</material>

		<!--Defining Red Material-->
		<material name = "Red">
			<color rgba = "0.8 0 0 1"/>
		</material>

		<!--Defining Blue Material-->
		<material name = "Blue">
			<color rgba = "0 0 0.8 1"/>
		</material>

		<!--Defining Base Parameters-->
		<xacro:property name = "base_height" value = "0.02"/>
		<xacro:property name = "base_radius" value = "0.15"/>
		<xacro:property name = "base_mass" value = "5"/> <!--Mass in kg-->

		<!--Defining Hokuyo Laser Scanner Property-->
		<xacro:property name = "hokuyo_size" value = "0.05"/>

		<!--using wheels from another xacro file-->
		<xacro:include filename = "$(find differential_drive_robot)/urdf/wheel.xacro"/>
		<!--using caster wheel from another xacro file-->
		<xacro:include filename = "$(find differential_drive_robot)/urdf/caster_wheel.xacro"/>

		<!--Defining Macro for the interia of the cylinder-->
		<xacro:macro name="cylinder_inertia" params="m r h">
			<interial>
				<mass value = "${m}"/>
				<inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
								iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
								izz="${m*r*r/2}" />
			</interial>
		</xacro:macro>

		<!--////////////////////////////////// Defining Base Footprint /////////////////////////////////-->
		<!--Base footprint is a friction less frame right below the base link origin-->
		<link name = "base_footprint">
			<!--Defining Visual Property-->
			<visual>
				<geometry>
					<box size = "0.001 0.001 0.001"/>
				</geometry>
				<!--origin-->
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
			</visual>
			<!--Defining inertia-->
			<inertial>
				<mass value = "0.0001"/>
				<inertia ixx = "0.0001" ixy = "0" ixz = "0" iyy = "0.0001" iyz = "0" izz = "0.0001"/>
			</inertial>
		</link>

		<!--Defininfg Joint-->
		<joint name = "base_footprint_joint" type = "fixed">
			<!--Parent link-->
			<parent link = "base_footprint"/>
			<!--Child Link-->
			<child link = "base_link"/>
			<!--origin-->
			<origin xyz = "0 0 0.04" rpy = "0 0 0"/>
		</joint>

		<!--////////////////////////////////// Defining Base Link /////////////////////////////////-->
		<link name = "base_link">
			<!--Defining Visual Properties-->
			<visual>
				<geometry>
					<cylinder length = "${base_height}" radius = "${base_radius}"/>
				</geometry>
				<!--Defining Origin-->
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<!--Defining Material-->
				<material name = "White"/>
			</visual>
			<!--Collision Property-->
			<collision>
				<geometry>
					<cylinder length = "${base_height}" radius = "${base_radius}"/>
				</geometry>
				<!--Defining Origin-->
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
			</collision>
			<!--Defining Inertia-->
			<cylinder_inertia m = "${base_mass}" h = "${base_height}" r = "${base_radius}"/>
		</link>

		<!--////////////////////////////////// Defining Caster Wheel Front /////////////////////////////////-->
		<caster_wheel fb = "front" parent = "base_link" X = "0" Y = "0.02" jX = "0.115" jY = "0.0" jZ = "0.007"/>

		<!--////////////////////////////////// Defining Caster Wheel Back /////////////////////////////////-->
		<caster_wheel fb = "back" parent = "base_link" X = "0.02" Y = "0.02" jX = "-0.135" jY = "0.0" jZ = "0.009"/>

		<!--////////////////////////////////// Defining Left Wheel /////////////////////////////////-->
		<wheel fb = "front" lr = "left" parent = "base_link" translateX = "0" translateY = "0.5" flipY = "1"/>

		<!--////////////////////////////////// Defining Right Wheel /////////////////////////////////-->
		<wheel fb = "front" lr = "right" parent = "base_link" translateX = "0" translateY = "-0.5" flipY = "1"/>

		<!--////////////////////////////////// Defining Hokuyo Laser Scanner /////////////////////////////////-->
		<link name = "hokuyo_link">
			<visual>
				<!--Defining Visual properties-->
				<geometry>
					<box size = "${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
				</geometry>
				<!--Defining Origin-->
				<origin xyz = "0 0 0" rpy = "0 0 0"/>
				<!--Defining Material -->
				<material name= "Blue"/>
			</visual>
		</link>

		<!--Defining Joint-->
		<joint name = "hokuyo_joint" type = "fixed">
			<!--Parent Link-->
			<parent link = "base_link"/>
			<!--Child Link-->
			<child link = "hokuyo_link"/>
			<!--Defining Origin-->
			<origin xyz = "${base_radius - hokuyo_size/2} 0 ${base_height + hokuyo_size/4}" rpy = "0 0 0"/>
		</joint>

</robot>
